In [28]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already satisfied: sklearn in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (0.0)
Requirement already satisfied: scikit-learn in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (from sklearn) (0.24.2)
Requirement already satisfied: scipy>=0.19.1 in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.5.4)
Requirement already satisfied: numpy>=1.13.3 in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (from scikit-learn->sklearn) (2.2.0)

In [29]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

Requirement already satisfied: joblib in /Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages (1.0.1)

In [30]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [31]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna().replace({'CONFIRMED': 0, 'CANDIDATE': 1, 'FALSE POSITIVE': 2})
df.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,0,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,2,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,0,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,0,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

# Select your features (columns)

In [37]:
dfCorr = df.corr()
dfCorr1 = dfCorr[['koi_disposition']].sort_values(by='koi_disposition', ascending=False)
dfCorr1.head(10)

                 koi_disposition
koi_disposition         1.000000
koi_fpflag_ss           0.489354
koi_fpflag_co           0.451280
koi_steff_err1          0.395892
koi_fpflag_nt           0.374387
koi_fpflag_ec           0.340812
koi_teq                 0.251577
koi_depth               0.247170
koi_model_snr           0.215935
koi_steff               0.191013

In [42]:
# Set features. This will also be used as your x values.
selected_features = df[['koi_fpflag_ss','koi_fpflag_co','koi_fpflag_nt','koi_fpflag_ec','koi_teq','koi_depth','koi_model_snr']]
X = selected_features
X

,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_nt,koi_fpflag_ec,koi_teq,koi_depth,koi_model_snr
0,0,0,0,0,443,874.8,25.8
1,1,0,0,0,638,10829.0,76.3
2,1,0,0,0,1395,8079.2,505.6
3,0,0,0,0,1406,603.3,40.9
4,0,0,0,0,1160,686.0,40.2
...,...,...,...,...,...,...,...
6986,0,0,0,1,929,87.7,8.4
6987,1,1,0,0,2088,1579.2,453.3
6988,0,0,0,0,1608,48.5,10.6
6989,0,1,0,0,2218,103.6,12.3
6990,0,1,0,1,1266,76.7,8.2

# Create a Train Test Split

Use `koi_disposition` for the y values

In [41]:
y = df[['koi_disposition']]
y

      koi_disposition
0                   0
1                   2
2                   2
3                   0
4                   0
...               ...
6986                2
6987                2
6988                1
6989                2
6990                2

[6991 rows x 1 columns]

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

X_train.head()

,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_nt,koi_fpflag_ec,koi_teq,koi_depth,koi_model_snr
6122,0,0,0,0,1017,123.1,10.8
6370,1,0,0,1,1867,114.6,13.8
2879,0,0,1,0,989,641.1,254.3
107,0,0,0,0,696,875.4,38.4
29,0,0,0,0,1103,9802.0,696.5

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [57]:
# Scale your data

from sklearn.preprocessing import MinMaxScaler

X_scaler = MinMaxScaler().fit(X_train)

# Train the Model

In [63]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

target_names = ['CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE']

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

model2 = KNeighborsClassifier(n_neighbors=7)
model2.fit(X_train_scaled, y_train)

print(f"Training Data Score: {model2.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model2.score(X_test_scaled, y_test)}")

predictions = model2.predict(X_test_scaled)
report = classification_report(predictions, y_test, target_names=target_names, output_dict=True)
report = pd.DataFrame(data=report)
print(report)

/Users/adrianmarceloflorespedraza/opt/anaconda3/envs/py36/lib/python3.6/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

Training Data Score: 0.890520694259012
Testing Data Score: 0.8649885583524027
            CONFIRMED   CANDIDATE  FALSE POSITIVE  accuracy    macro avg  \
precision    0.766529    0.705596        0.997655  0.864989     0.823260
recall       0.763374    0.736041        0.980415  0.864989     0.826610
f1-score     0.764948    0.720497        0.988960  0.864989     0.824802
support    486.000000  394.000000      868.000000  0.864989  1748.000000

           weighted avg
precision      0.867565
recall         0.864989
f1-score       0.866166
support     1748.000000

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# Create the GridSearchCV model

In [ ]:
# Train the model with GridSearch

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)